services:
  - type: web
    name: n8n
    env: docker
    image:
      url: docker.io/n8n/n8n:latest
    instanceType: free
    envVars:
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: N8N_SECURE_COOKIE
        value: false # Important for initial setup on Render
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
