services:
  - type: web
    name: n8n
    env: docker
    plan: free 
    image:
      url: docker.io/n8n/n8n:latest
    envVars:
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: N8N_SECURE_COOKIE
        value: false
    disk: 
      name: n8n-data
      mountPath: /home/node/.n8n
