services:
  # Service 1: The n8n application itself, running as a Private Service.
  # It has the persistent disk and does the actual work.
  - type: pserv # 'pserv' stands for Private Service
    name: n8n-app
    env: docker
    plan: free
    image:
      url: docker.io/n8n/n8n:latest
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      # This tells n8n its public address for webhooks to work correctly.
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-proxy # The name of our proxy service below
          property: url


